In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("cars_data.csv")
df = df.rename(columns={'kolimeter': 'kilometer', 'feul_type': 'fuel_type'})
df

,name,city,price,model,kilometer,fuel_type,engine,transmission
0,Honda Civic 2021 1.5 RS Turbo for Sale,Abbottabad,PKR 67 lacs,2021,"88,000 km",Petrol,1500 cc,Automatic
1,Honda Civic 2019 Oriel 1.8 i-VTEC CVT for Sale,Peshawar,PKR 61.5 lacs,2019,"68,425 km",Petrol,1800 cc,Automatic
2,Toyota Hilux 2012 D-4D Automatic for Sale,Peshawar,PKR 65.5 lacs,2012,"132,000 km",Diesel,3000 cc,Automatic
3,Toyota Prius Alpha 2018 S Touring Selection G...,Peshawar,PKR 98.5 lacs,2018,"35,000 km",Hybrid,1800 cc,Automatic
4,Toyota Corolla Fielder 2017 Hybrid G WB for...,Peshawar,PKR 62 lacs,2017,"165,044 km",Hybrid,1500 cc,Automatic
...,...,...,...,...,...,...,...,...
4989,Suzuki Cultus 2007 VXR (CNG) for Sale,Mardan,PKR 11.9 lacs,2007,"80,000 km",Petrol,1000 cc,Manual
4990,Suzuki Alto 1998 for Sale,Peshawar,PKR 12.7 lacs,1998,"120,000 km",Petrol,660 cc,Automatic
4991,Suzuki Mehran 2004 VX for Sale,Charsadda,PKR 5.5 lacs,2004,"100,000 km",Petrol,800 cc,Manual
4992,Suzuki Alto 2011 VXR for Sale,Peshawar,PKR 14.99 lacs,2011,"95,000 km",Petrol,1000 cc,Manual
4993,Toyota Corolla 1986 GL Saloon for Sale,Charsadda,PKR 8.8 lacs,1986,"200,000 km",CNG,1500 cc,Manual

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4994 entries, 0 to 4993
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          4994 non-null   object
 1   city          4994 non-null   object
 2   price         4994 non-null   object
 3   model         4994 non-null   int64
 4   kilometer     4994 non-null   object
 5   fuel_type     4994 non-null   object
 6   engine        4994 non-null   object
 7   transmission  4994 non-null   object
dtypes: int64(1), object(7)
memory usage: 312.3+ KB

In [4]:
df['city'] = df['city'].str.strip()
df.rename(columns={'model': 'model_year'}, inplace=True)

In [5]:
import numpy as np

def clean_price(x):
    x = str(x).lower().replace('pkr', '').strip()  # convert to string first

    if 'crore' in x:
        return float(x.replace('crore', '').strip()) * 10000000
    if 'lac' in x:
        return float(x.replace('lacs', '').replace('lac', '').strip()) * 100000

    try:
        return float(x)  # if it's already a number
    except:
        return np.nan

In [6]:
df['price'] = df['price'].apply(clean_price)
df['price'] = df['price'].fillna(9800000)
df['price'].isnull().sum()

df['price'] = df['price'].astype(int)
df.head(5)

,name,city,price,model_year,kilometer,fuel_type,engine,transmission
0,Honda Civic 2021 1.5 RS Turbo for Sale,Abbottabad,6700000,2021,"88,000 km",Petrol,1500 cc,Automatic
1,Honda Civic 2019 Oriel 1.8 i-VTEC CVT for Sale,Peshawar,6150000,2019,"68,425 km",Petrol,1800 cc,Automatic
2,Toyota Hilux 2012 D-4D Automatic for Sale,Peshawar,6550000,2012,"132,000 km",Diesel,3000 cc,Automatic
3,Toyota Prius Alpha 2018 S Touring Selection G...,Peshawar,9850000,2018,"35,000 km",Hybrid,1800 cc,Automatic
4,Toyota Corolla Fielder 2017 Hybrid G WB for...,Peshawar,6200000,2017,"165,044 km",Hybrid,1500 cc,Automatic

In [7]:
df['kilometer'] = df['kilometer'].str.replace(',', '').str.replace(' km', '')
df['engine'] = df['engine'].str.replace(' cc', '').str.replace(' kWh','')
df.head(5)
df['kilometer'] = pd.to_numeric(df['kilometer'], errors='coerce')
df['kilometer'] = df['kilometer'].astype('Int64')
df['engine'] = pd.to_numeric(df['engine'], errors='coerce')   
df['engine'] = df['engine'].astype('Int64')

In [8]:
df['name'] = df['name'].str.replace(r'\b(19|20)\d{2}\b', '', regex=True)
df['name'] = df['name'].str.replace(r'\bfor sale\b', '', regex=True, case=False)
df['name'] = df['name'].str.replace(r'\s+', ' ', regex=True).str.strip()
df.head()

,name,city,price,model_year,kilometer,fuel_type,engine,transmission
0,Honda Civic 1.5 RS Turbo,Abbottabad,6700000,2021,88000,Petrol,1500,Automatic
1,Honda Civic Oriel 1.8 i-VTEC CVT,Peshawar,6150000,2019,68425,Petrol,1800,Automatic
2,Toyota Hilux D-4D Automatic,Peshawar,6550000,2012,132000,Diesel,3000,Automatic
3,Toyota Prius Alpha S Touring Selection GR Sport,Peshawar,9850000,2018,35000,Hybrid,1800,Automatic
4,Toyota Corolla Fielder Hybrid G WB,Peshawar,6200000,2017,165044,Hybrid,1500,Automatic

In [9]:
pd.set_option('display.max_rows', None)

In [10]:
df['city'] = df['city'].str.replace('Dera ismail khan','DI Khan').str.replace('Malakand Agency','Malakand').str.strip()
df['brand'] = df['name'].str.split().str[0]
df['model_name'] = df['name'].str.split().str[1]
df.head()

,name,city,price,model_year,kilometer,fuel_type,engine,transmission,brand,model_name
0,Honda Civic 1.5 RS Turbo,Abbottabad,6700000,2021,88000,Petrol,1500,Automatic,Honda,Civic
1,Honda Civic Oriel 1.8 i-VTEC CVT,Peshawar,6150000,2019,68425,Petrol,1800,Automatic,Honda,Civic
2,Toyota Hilux D-4D Automatic,Peshawar,6550000,2012,132000,Diesel,3000,Automatic,Toyota,Hilux
3,Toyota Prius Alpha S Touring Selection GR Sport,Peshawar,9850000,2018,35000,Hybrid,1800,Automatic,Toyota,Prius
4,Toyota Corolla Fielder Hybrid G WB,Peshawar,6200000,2017,165044,Hybrid,1500,Automatic,Toyota,Corolla

In [32]:
df.sort_values(by='kilometer', ascending=False).tail(300)

,name,city,price,model_year,kilometer,fuel_type,engine,transmission,brand,model_name
779,Toyota Fortuner GR-S,Peshawar,21000000,2025,6000,Diesel,2800,Automatic,Toyota,Fortuner
3939,Suzuki Alto VXL AGS,Peshawar,3800000,2024,5947,Petrol,660,Automatic,Suzuki,Alto
3573,Suzuki Alto VXR,Peshawar,2850000,2024,5900,Petrol,660,Manual,Suzuki,Alto
2678,Suzuki Mehran VXR,Haripur,495000,1999,5500,Petrol,800,Manual,Suzuki,Mehran
4909,Nissan Sunny,Mansehra,850000,2000,5500,Petrol,1500,Automatic,Nissan,Sunny
1732,Suzuki Wagon R Hybrid FZ,Peshawar,3395000,2022,5300,Hybrid,660,Automatic,Suzuki,Wagon
3715,Toyota Corolla DX Saloon,Peshawar,1500000,1986,5000,Petrol,1300,Manual,Toyota,Corolla
3880,Suzuki Alto VXR,Mardan,1400000,2012,5000,Petrol,1000,Manual,Suzuki,Alto
2867,Toyota Corolla GLi 1.3 VVTi,Nowshera,2300000,2010,5000,Petrol,1300,Manual,Toyota,Corolla
1828,Suzuki Cultus VXR,Abbottabad,825000,2000,5000,Petrol,1000,Manual,Suzuki,Cultus
3671,Toyota Corolla Altis Grande X CVT-i 1.8 Black ...,Peshawar,8120000,2025,5000,Petrol,1800,Automatic,Toyota,Corolla
1675,Toyota Corolla XLi VVTi,Kohat,3000000,2011,5000,Petrol,1300,Manual,Toyota,Corolla
804,Suzuki Cultus VXR,Bannu,1060000,2007,5000,Petrol,1000,Manual,Suzuki,Cultus
3935,Honda Civic 11th Generation RS,Peshawar,10500000,2025,5000,Petrol,1500,Automatic,Honda,Civic
3246,Suzuki Mehran VXR,Nowshera,850000,2007,5000,Petrol,800,Manual,Suzuki,Mehran
2489,MG HS PHEV,Peshawar,9650000,2025,4853,Hybrid,1500,Automatic,MG,HS
4246,Toyota Corolla Altis X Automatic 1.6,Peshawar,6500000,2022,4800,Petrol,1600,Automatic,Toyota,Corolla
483,Toyota Corolla Cross 1.8 HEV X,Peshawar,9200000,2025,4600,Hybrid,1800,Automatic,Toyota,Corolla
1566,Toyota Corolla Cross 1.8 HEV X,Peshawar,9200000,2025,4600,Hybrid,1800,Automatic,Toyota,Corolla
589,Suzuki Bolan,Mardan,480000,1984,4552,Petrol,800,Manual,Suzuki,Bolan
608,Toyota Corolla 8th (E110) Generation GLi 1.6,Nowshera,1500000,1998,4500,Petrol,1600,Manual,Toyota,Corolla
1757,Suzuki Alto VXR,Abbottabad,3050000,2025,4500,Petrol,660,Manual,Suzuki,Alto
3454,Suzuki Alto VXL AGS Upgraded,Peshawar,3390000,2025,4500,Petrol,660,Automatic,Suzuki,Alto
575,Toyota Fortuner GR-S,Peshawar,21000000,2023,4300,Diesel,2800,Automatic,Toyota,Fortuner
2805,Honda Civic RS,Peshawar,9500000,2023,4300,Petrol,1500,Automatic,Honda,Civic
3033,Suzuki Mehran VXR,Abbottabad,980000,2007,4200,Petrol,800,Manual,Suzuki,Mehran
637,Haval H6 PHEV,Peshawar,14000000,2025,4000,Hybrid,1500,Automatic,Haval,H6
3953,Honda Civic 11th Generation RS,Peshawar,10200000,2025,4000,Petrol,1500,Automatic,Honda,Civic
2090,Haval H6 PHEV,Peshawar,14000000,2025,4000,Hybrid,1500,Automatic,Haval,H6
2463,Toyota Corolla 9th (E120) Generation SE Saloon,Peshawar,1950000,2003,4000,Petrol,1600,Manual,Toyota,Corolla
4301,Toyota Corolla,Mansehra,6600000,2023,4000,Petrol,1600,Automatic,Toyota,Corolla
4228,Toyota Hilux Revo GR-S,Peshawar,16000000,2023,3800,Diesel,2800,Automatic,Toyota,Hilux
455,Toyota Corolla Altis Grande X CVT-i 1.8 Black ...,Peshawar,8300000,2025,3500,Petrol,1800,Automatic,Toyota,Corolla
2407,Suzuki Bolan VX Euro II,Peshawar,1450000,2015,3500,Petrol,800,Manual,Suzuki,Bolan
3414,Suzuki Bolan VX,Mansehra,1160000,2010,3050,Petrol,800,Manual,Suzuki,Bolan
284,Mazda Flair XG,Peshawar,3450000,2025,3000,Petrol,660,Automatic,Mazda,Flair
1284,Toyota Corolla X 1.3,Swabi,2950000,2006,3000,Petrol,1300,Automatic,Toyota,Corolla
1572,Toyota Hilux Revo GR-S,Peshawar,17100000,2025,3000,Diesel,2800,Automatic,Toyota,Hilux
2250,Suzuki Alto,Peshawar,1150000,2008,3000,Petrol,1000,Manual,Suzuki,Alto
485,Toyota Hilux Revo GR-S,Peshawar,17100000,2025,3000,Diesel,2800,Automatic,Toyota,Hilux
1269,Suzuki Alto VXR (CNG),Mardan,1280000,2012,2888,CNG,1000,Manual,Suzuki,Alto
3139,Haval H6 PHEV,Peshawar,13400000,2025,2800,Hybrid,1500,Automatic,Haval,H6
781,Haval H6 PHEV,Peshawar,13400000,2025,2800,Hybrid,1500,Automatic,Haval,H6
3252,Honda Civic 6th Generation VTi 1.6,Peshawar,1220000,1996,2800,Petrol,1600,Manual,Honda,Civic
1520,Honda N Wgn G,Mardan,3650000,2023,2800,Petrol,660,Automatic,Honda,N
484,Haval H6 PHEV,Peshawar,13400000,2025,2600,PHEV,1500,DHT,Haval,H6
1567,Haval H6 PHEV,Peshawar,13400000,2025,2600,PHEV,1500,DHT,Haval,H6
719,Suzuki Bolan VX,Abbottabad,1350000,2012,2580,CNG,800,Manual,Suzuki,Bolan
3949,Suzuki Bolan VX Euro II,Peshawar,2390000,2024,2200,Petrol,800,Manual,Suzuki,Bolan
1774,Toyota Corolla XLi VVTi,Kohat,2950000,2012,2200,Petrol,1300,Manual,Toyota,Corolla
1115,Suzuki Alto VXR Upgraded,Mansehra,3150000,2025,2200,Petrol,660,Manual,Suzuki,Alto
3898,Honda HR-V VTi-S,Mardan,7050000,2023,2061,Petrol,1500,Automatic,Honda,HR-V
3111,Suzuki Mehran,Peshawar,1350000,2016,2016,Petrol,800,Manual,Suzuki,Mehran
4493,Suzuki Wagon R VXL,Peshawar,1950000,2015,2007,Petrol,1000,Manual,Suzuki,Wagon
1455,Suzuki Khyber GA,Abbottabad,540000,2000,2000,Petrol,1000,Manual,Suzuki,Khyber
2978,Suzuki Mehran VX (CNG),Karak,710000,2008,2000,Petrol,800,Manual,Suzuki,Mehran
24,Toyota Yaris Sedan GLI CVT 1.3,Mardan,5200000,2025,2000,Petrol,1300,Automatic,Toyota,Yaris
4023,Toyota Corolla 9th (E120) Generation XLi,Mansehra,2250000,2007,2000,Petrol,1300,Manual,Toyota,Corolla
2202,Toyota Prius S 1.5,Bannu,2900000,2010,2000,Hybrid,1497,Automatic,Toyota,Prius
2946,Honda Civic,Peshawar,950000,1987,2000,Petrol,1300,Manual,Honda,Civic
2804,Toyota Aqua,Peshawar,3450000,2013,1999,Hybrid,1500,Automatic,Toyota,Aqua
2287,Toyota Corolla GLi 1.6,Nowshera,1400000,1996,1996,Petrol,1600,Manual,Toyota,Corolla
2560,Suzuki Mehran VX,Peshawar,590000,1992,1992,Petrol,800,Manual,Suzuki,Mehran
1046,Suzuki FX GA,Abbottabad,270000,1988,1988,Petrol,800,Manual,Suzuki,FX
4920,Toyota 86,Peshawar,550000,1986,1918,CNG,1300,Manual,Toyota,86
4268,Suzuki Swift GLX CVT,Abbottabad,5150000,2025,1700,Petrol,1200,Automatic,Suzuki,Swift
1673,Toyota Pixis Epoch X,Abbottabad,4425000,2024,1700,Petrol,660,Automatic,Toyota,Pixis
3051,Changan Alsvin Black Edition,Peshawar,4880000,2026,1700,Petrol,1500,Automatic,Changan,Alsvin
521,Toyota Pixis Epoch X,Abbottabad,4425000,2024,1700,Petrol,660,Automatic,Toyota,Pixis
3113,KIA Picanto 1.0 AT,Swabi,2700000,2020,1600,Petrol,1000,Automatic,KIA,Picanto
2312,Subaru Justy,Mardan,850000,1993,1515,Petrol,1000,Manual,Subaru,Justy
4269,Toyota Corolla GLi Automatic 1.3 VVTi,Charsadda,4350000,2016,1500,Petrol,1300,Automatic,Toyota,Corolla
4771,Toyota Corolla,Peshawar,800000,1986,1500,Petrol,1300,Manual,Toyota,Corolla
2352,BMW 7 Series 730d,Peshawar,4200000,2004,1500,Diesel,3000,Automatic,BMW,7
53,Toyota Hilux Revo GR-S,Peshawar,17600000,2025,1450,Diesel,2800,Automatic,Toyota,Hilux
1152,Suzuki Alto E,Topi,2450000,2011,1432,Petrol,660,Automatic,Suzuki,Alto
3061,Suzuki Mehran VXR Euro II,Haripur,1120000,2013,1400,Petrol,800,Manual,Suzuki,Mehran
293,Honda City 5th (GM2) Generation 1.3 i-VTEC Pro...,Abbottabad,5500000,2019,1300,Petrol,1300,Automatic,Honda,City
3381,Jeep M 151 Standard,Nowshera,865000,1976,1300,Diesel,2300,Manual,Jeep,M
3477,Toyota Corolla XLi VVTi Limited Edition,Charsadda,2450000,2010,1287,Petrol,1300,Manual,Toyota,Corolla
3637,Toyota Corolla Hybrid S,Mardan,4050000,2018,1235,Hybrid,1500,Automatic,Toyota,Corolla
1694,Toyota Probox,Swabi,2350000,2006,1234,Petrol,1300,Automatic,Toyota,Probox
64,Toyota Premio X 1.8,Peshawar,3350000,2007,1232,Petrol,1800,Automatic,Toyota,Premio
645,Toyota Corolla Fielder Hybrid,Kohat,3900000,2013,1230,Hybrid,1500,Automatic,Toyota,Corolla
3562,Toyota Corolla 2.0D,Abbottabad,1900000,2007,1212,Diesel,2000,Manual,Toyota,Corolla
4074,Toyota Land Cruiser,Gari habibullah,2800000,1984,1200,Diesel,2100,Manual,Toyota,Land
1517,Toyota Corolla Fielder X G Edition,Bannu,4450000,2007,1111,Petrol,1600,Automatic,Toyota,Corolla
4882,Nissan Bluebird Sylphy 15M Four,Peshawar,1490000,2007,1110,Petrol,1500,Automatic,Nissan,Bluebird
1610,Honda Civic Reborn MXST (Hybrid),Peshawar,2850000,2006,1037,Hybrid,1300,Automatic,Honda,Civic
462,Toyota Corolla,Abbottabad,550000,1982,1000,Petrol,1500,Manual,Toyota,Corolla
4871,Honda Civic VTi Oriel 1.6,Swabi,1650000,2000,1000,Petrol,1600,Manual,Honda,Civic
4971,Suzuki Mehran VXR,Abbottabad,630000,2004,1000,CNG,800,Manual,Suzuki,Mehran
2592,Jeep CJ 5,Peshawar,3850000,1975,1000,Diesel,2000,Automatic,Jeep,CJ
26,Honda Fit 1.5 Hybrid Smart Selection,Swabi,3450000,2014,1000,Hybrid,1500,Automatic,Honda,Fit
2594,Toyota Corolla DX,Swabi,850000,1988,1000,Petrol,1300,Manual,Toyota,Corolla
3410,Toyota Corolla 9th (E120) Generation XLi,Haripur,2500000,2006,1000,CNG,1300,Manual,Toyota,Corolla
344,Toyota Corolla 8th (E110) Generation XE Limited,Peshawar,1300000,1996,1000,Petrol,1300,Manual,Toyota,Corolla
4849,Suzuki Potohar,Peshawar,1150000,1996,1000,Petrol,800,Manual,Suzuki,Potohar
3409,Suzuki Cultus,Peshawar,860000,2001,1000,Petrol,1000,Manual,Suzuki,Cultus
456,Toyota Raize Z,Peshawar,6450000,2020,1000,Petrol,1000,Automatic,Toyota,Raize
581,Suzuki Margalla GL,Peshawar,465000,1995,1000,Petrol,1300,Manual,Suzuki,Margalla
647,Suzuki Mehran VXR,Abbottabad,475000,1998,1000,Petrol,800,Manual,Suzuki,Mehran
4606,Suzuki Alto VXR,Charsadda,1450000,2009,1000,Petrol,1000,Manual,Suzuki,Alto
3203,Suzuki FX GA,DI Khan,400000,1988,1000,Petrol,800,Manual,Suzuki,FX
3819,Toyota Corolla 8th (E110) Generation GLi 1.6,Swabi,1450000,1999,1000,CNG,1600,Manual,Toyota,Corolla
88,Toyota Passo G 1.0,Peshawar,1820000,2008,1000,Petrol,1000,Automatic,Toyota,Passo
14,Daihatsu Cuore CX Automatic,Peshawar,1040000,2007,1000,Petrol,800,Automatic,Daihatsu,Cuore
4695,Suzuki Cultus VXL,Nowshera cantt,950000,2006,1000,Petrol,1000,Manual,Suzuki,Cultus
751,Suzuki Mehran VXR,Peshawar,900000,2009,1000,Petrol,800,Manual,Suzuki,Mehran
792,Changan Karvaan Plus,DI Khan,2100000,2021,1000,Petrol,1000,Manual,Changan,Karvaan
915,Toyota Corolla DX,Peshawar,950000,1986,999,Petrol,1300,Manual,Toyota,Corolla
3182,Suzuki Every VX,Peshawar,2495000,2025,900,Petrol,660,Manual,Suzuki,Every
1847,Toyota Corolla Altis Grande X CVT-i 1.8 Beige ...,Peshawar,7350000,2021,870,Petrol,1800,Automatic,Toyota,Corolla
599,Toyota Corolla Altis Grande X CVT-i 1.8 Beige ...,Peshawar,7350000,2021,870,Petrol,1800,Automatic,Toyota,Corolla
3688,Suzuki Mehran VXR,Swabi,570000,2006,869,Petrol,800,Manual,Suzuki,Mehran
576,Suzuki Baleno GLi P,Swabi,1100000,2001,855,Petrol,1300,Manual,Suzuki,Baleno
1272,Suzuki FX,Peshawar,300000,1984,800,Petrol,800,Manual,Suzuki,FX
1188,Suzuki Bolan,Mansehra,2550000,2025,600,Petrol,800,Manual,Suzuki,Bolan
2132,Jeep CJ 5,Mansehra,2500000,1976,582,Diesel,3600,Manual,Jeep,CJ
438,Suzuki Every VXR,Peshawar,3050000,2025,523,Petrol,660,Manual,Suzuki,Every
4277,Haval H6 PHEV,Peshawar,14500000,2025,377,Hybrid,1500,Automatic,Haval,H6
1140,Toyota Corolla 9th (E120) Generation XLi,Kohat,2150000,2005,340,Petrol,1300,Manual,Toyota,Corolla
4574,Toyota Corolla 8th (E110) Generation GLi 1.6,Peshawar,1380000,1996,310,Petrol,1600,Manual,Toyota,Corolla
3870,Toyota Corolla XLi VVTi,Peshawar,3100000,2015,300,Petrol,1300,Manual,Toyota,Corolla
3745,Suzuki Mehran VXR,Kohat,670000,1990,300,Petrol,800,Manual,Suzuki,Mehran
382,Toyota Corolla XLi,Peshawar,2175000,2004,292,Petrol,1300,Manual,Toyota,Corolla
32,Toyota Corolla 9th (E120) Generation SE Saloon...,Mardan,2075000,2004,270,CNG,1600,Automatic,Toyota,Corolla
3622,Nissan Sunny,Peshawar,480000,1989,258,Petrol,1500,Manual,Nissan,Sunny
2889,Suzuki Every VXR,Charsadda,2670000,2025,250,Petrol,660,Manual,Suzuki,Every
2757,Toyota Prius,Peshawar,4500000,2012,200,Hybrid,1800,Automatic,Toyota,Prius
2755,Toyota Prius S LED Edition 1.8,Peshawar,4500000,2012,200,Hybrid,1800,Automatic,Toyota,Prius
3204,Toyota Vitz U 1.0,Swabi,2450000,2010,197,Petrol,1000,Automatic,Toyota,Vitz
709,Toyota Corolla Altis Grande X CVT-i 1.8 Black ...,Charsadda,8050000,2025,190,Petrol,1800,Automatic,Toyota,Corolla
2475,Toyota Corolla Altis Grande X CVT-i 1.8 Black ...,Charsadda,8050000,2025,190,Petrol,1800,Automatic,Toyota,Corolla
3695,Suzuki Every 6th Generation (Imported) PC,Peshawar,2670000,2019,190,Petrol,660,Automatic,Suzuki,Every
3681,Toyota Land Cruiser,Akora khattak,2650000,1986,180,Diesel,3000,Manual,Toyota,Land
2389,Daihatsu Charade CL,Peshawar,480000,1987,180,Petrol,1000,Manual,Daihatsu,Charade
2235,Toyota Premio X 1.8,Mardan,3879999,2006,178,Petrol,1800,Automatic,Toyota,Premio
2260,Toyota Premio X EX Package 1.8,Mardan,6000000,2012,170,Petrol,1800,Automatic,Toyota,Premio
1034,Toyota Corolla SE Saloon Automatic,Abbottabad,2280000,2003,165,Petrol,1600,Automatic,Toyota,Corolla
3701,Toyota Aqua S,Peshawar,4450000,2015,165,Hybrid,1500,Automatic,Toyota,Aqua
945,Toyota Vitz,Peshawar,2300000,2008,160,Petrol,1000,Automatic,Toyota,Vitz
1156,Toyota Vitz F 1.0,Charsadda,1950000,2005,158,Petrol,1000,Automatic,Toyota,Vitz
2540,Toyota Aqua G Sports,Peshawar,4550000,2016,158,Hybrid,1500,Automatic,Toyota,Aqua
3531,Toyota Aqua GS,Peshawar,4600000,2016,155,Hybrid,1500,Automatic,Toyota,Aqua
918,Toyota Corolla XLi VVTi,Swabi,3400000,2014,150,Petrol,1300,Manual,Toyota,Corolla
3930,Toyota Corolla XE,Swabi,1300000,1999,150,Petrol,1300,Automatic,Toyota,Corolla
2187,Daihatsu Mira ES,Mardan,2570000,2014,150,Petrol,660,Automatic,Daihatsu,Mira
3498,Toyota Land Cruiser,Peshawar,2900000,1984,150,Diesel,4200,Manual,Toyota,Land
3997,FAW Carrier,Akora khattak,1250000,2020,150,Petrol,1000,Manual,FAW,Carrier
2928,Honda Civic Oriel 1.8 i-VTEC CVT,Peshawar,4650000,2017,150,Petrol,1800,Automatic,Honda,Civic
78,Toyota Corolla Altis Grande X CVT-i 1.8 Black ...,Abbottabad,6650000,2022,148,Petrol,1800,Automatic,Toyota,Corolla
277,Toyota Corolla Altis Grande X CVT-i 1.8 Black ...,Abbottabad,6650000,2022,148,Petrol,1800,Automatic,Toyota,Corolla
1468,Toyota Vitz Jewela Smart Stop Package 1.3,Peshawar,3200000,2011,144,Petrol,1300,Automatic,Toyota,Vitz
3933,Suzuki Alto L Upgrade,Abbottabad,3679999,2022,143,Petrol,660,Automatic,Suzuki,Alto
3120,Toyota Corolla 9th (E120) Generation Altis Aut...,Swabi,2400000,2006,142,Petrol,1800,Automatic,Toyota,Corolla
391,Toyota Corolla GLi 1.3 VVTi,Mardan,3045000,2011,140,Petrol,1300,Manual,Toyota,Corolla
4028,Toyota Vitz F 1.0,Abbottabad,2130000,2005,140,Petrol,1000,Automatic,Toyota,Vitz
1544,Suzuki Alto VXL AGS Upgraded,Peshawar,3400000,2026,140,Petrol,660,Automatic,Suzuki,Alto
3615,Suzuki FX GA,Mardan,409999,1987,140,Petrol,800,Manual,Suzuki,FX
2833,Toyota Corolla GLi 1.3 VVTi,Peshawar,3100000,2013,136,Petrol,1300,Manual,Toyota,Corolla
1026,Daihatsu Mira ES,Karak,2400000,2014,136,Petrol,660,Automatic,Daihatsu,Mira
2408,Honda Civic Reborn VTi Oriel Prosmatec 1.8 i-VTEC,Peshawar,1900000,2006,135,Petrol,1800,Automatic,Honda,Civic
2825,Suzuki Wagon R,Peshawar,3800000,2021,134,Hybrid,660,Automatic,Suzuki,Wagon
1120,Toyota Corolla XLi VVTi,Peshawar,3000000,2014,130,Petrol,1300,Manual,Toyota,Corolla
1374,Suzuki Kei B Turbo,Abbottabad,1600000,2001,130,Petrol,660,Automatic,Suzuki,Kei
3676,Honda City Aspire Prosmatec 1.3 i-VTEC,Peshawar,3990000,2018,126,Petrol,1300,Automatic,Honda,City
3372,Honda Civic VTi Oriel Prosmatec 1.8 i-VTEC,Peshawar,3085000,2011,124,Petrol,1800,Automatic,Honda,Civic
1809,Toyota Prius S LED Edition 1.8,Peshawar,4380000,2013,124,Hybrid,1800,Automatic,Toyota,Prius
143,Suzuki Swift GL CVT Limited Edition,Peshawar,3975000,2022,123,Petrol,1200,Automatic,Suzuki,Swift
422,Toyota Corolla SE Limited,Peshawar,1900000,1995,123,Petrol,1500,Automatic,Toyota,Corolla
2477,Honda Civic VTi Oriel 1.8 i-VTEC,Abbottabad,2290000,2007,123,Petrol,1800,Manual,Honda,Civic
3220,Toyota Hiace,Haripur,2050000,1992,123,CNG,2000,Manual,Toyota,Hiace
3362,Toyota Corolla XLi VVTi,Mardan,3400000,2015,123,Petrol,1300,Manual,Toyota,Corolla
4816,Honda Civic 7th Generation (Facelift) EXi,Peshawar,1600000,2005,123,Petrol,1500,Manual,Honda,Civic
4513,Toyota Corolla,Peshawar,1400000,1993,123,Petrol,1500,Manual,Toyota,Corolla
3141,Toyota Corolla Axio X Special Edition 1.5,Peshawar,3550000,2007,123,Petrol,1500,Automatic,Toyota,Corolla
1769,Suzuki Cultus,Risalpur,980000,2001,123,Petrol,1000,Manual,Suzuki,Cultus
1804,Toyota Corolla GLi 1.3 VVTi,Peshawar,2700000,2009,123,Petrol,1300,Manual,Toyota,Corolla
1155,Honda Civic 7th Generation (Facelift) EXi,Takhtbai,1480000,2004,123,Petrol,1500,Manual,Honda,Civic
4559,Honda Civic VTi Oriel Prosmatec 1.6,Peshawar,1500000,2002,123,Petrol,1500,Automatic,Honda,Civic
2356,Toyota Vitz F 1.0,Peshawar,2250000,2007,120,Petrol,1000,Automatic,Toyota,Vitz
328,Toyota Passo G 1.0,Mardan,2190000,2008,120,Petrol,1000,Automatic,Toyota,Passo
1190,Toyota Corolla,Kohat,2000000,1998,112,Petrol,1500,Automatic,Toyota,Corolla
4577,Suzuki Margalla,Nowshera,640000,1994,111,CNG,1300,Manual,Suzuki,Margalla
2377,Toyota Land Cruiser,Abbottabad,12500000,2002,105,Diesel,4200,Manual,Toyota,Land
2581,Daihatsu Cuore CL,Haripur,950000,2008,100,Petrol,800,Manual,Daihatsu,Cuore
4789,Suzuki Potohar Basegrade,Peshawar,950000,1991,100,Petrol,1000,Manual,Suzuki,Potohar
2692,Toyota Corolla 8th (E110) Generation XE Limited,Mansehra,1430000,2000,100,CNG,1300,Manual,Toyota,Corolla
4317,Toyota Corolla Fielder Hybrid G WB,Nowshera cantt,6800000,2018,100,Hybrid,1500,Automatic,Toyota,Corolla
2382,Toyota Corolla GLi 1.3 VVTi,Bannu,2550000,2010,100,Petrol,1300,Manual,Toyota,Corolla
2954,Toyota Corolla XLi,DI Khan,1700000,2007,100,Petrol,1300,Manual,Toyota,Corolla
3183,Suzuki Baleno JXR,Nowshera cantt,1040000,2003,100,CNG,1300,Manual,Suzuki,Baleno
923,Suzuki Swift GLX CVT,Peshawar,5050000,2026,100,Petrol,1200,Automatic,Suzuki,Swift
3969,Toyota Corolla XLi VVTi,Mardan,2600000,2010,100,CNG,1300,Manual,Toyota,Corolla
3307,Toyota Cressida GL,Peshawar,2400000,1989,100,Petrol,3000,Manual,Toyota,Cressida
2375,Suzuki Mehran VXR,Kohat,760000,2006,100,Petrol,800,Manual,Suzuki,Mehran
764,Toyota Vitz F 1.0,Peshawar,2150000,2007,100,Petrol,1000,Automatic,Toyota,Vitz
2400,Toyota Corolla DX,Charsadda,1500000,1988,88,Petrol,1300,Manual,Toyota,Corolla
1102,Toyota Corolla Altis Grande CVT-i 1.8,Nowshera cantt,4900000,2015,86,Petrol,1800,Automatic,Toyota,Corolla
1760,Range Rover Sport First Edition,Peshawar,9500000,2007,80,Petrol,4200,Automatic,Range,Rover
1079,Honda City 6th Generation 1.2L CVT,Peshawar,5565000,2026,80,Petrol,1200,Automatic,Honda,City
4737,Toyota Vitz F 1.0,Peshawar,2000000,2003,70,Petrol,1000,Automatic,Toyota,Vitz
2597,Suzuki Margalla GL,Abbottabad,720000,1997,66,Petrol,1300,Manual,Suzuki,Margalla
3397,Suzuki Bolan VX Euro II,Abbottabad,1700000,2018,60,Petrol,800,Manual,Suzuki,Bolan
3308,Honda N Box Custom GL,Peshawar,3120000,2021,60,Petrol,658,Automatic,Honda,N
3684,Suzuki Bolan VX Euro II,Mardan,2300000,2024,42,Petrol,800,Manual,Suzuki,Bolan
2314,Suzuki Mehran,Mardan,770000,2007,40,Petrol,800,Manual,Suzuki,Mehran
693,Toyota Corolla 8th (E110) Generation XE,Haripur,1700000,1998,35,Petrol,1300,Manual,Toyota,Corolla
1927,Suzuki Bolan VX,Kohat,795000,2009,25,CNG,800,Manual,Suzuki,Bolan
2267,Suzuki Alto VXR Upgraded,Peshawar,3150000,2026,25,Petrol,660,Manual,Suzuki,Alto
862,Honda Civic 5th Generation EX,Nowshera cantt,800000,1995,22,Petrol,1500,Manual,Honda,Civic
822,Toyota Corolla Cross 1.8 HEV,Abbottabad,9300000,2026,20,Hybrid,1800,Automatic,Toyota,Corolla
3140,Honda HR-V e:HEV,Peshawar,8800000,2026,20,Hybrid,1500,Automatic,Honda,HR-V
782,Honda HR-V e:HEV,Peshawar,8800000,2026,20,Hybrid,1500,Automatic,Honda,HR-V
561,Toyota Corolla Altis 1.6 X CVT-i,Abbottabad,6950000,2026,20,Petrol,1600,Automatic,Toyota,Corolla
4143,Toyota Corolla Altis Grande X CVT-i 1.8 Beige ...,Abbottabad,8000000,2026,20,Petrol,1800,Automatic,Toyota,Corolla
860,Toyota Corolla Cross 1.8 HEV,Abbottabad,9300000,2026,20,Hybrid,1800,Automatic,Toyota,Corolla
838,Toyota Corolla SE Limited,Bannu,2050000,1994,20,Petrol,1500,Automatic,Toyota,Corolla
1721,Toyota Corolla Altis 1.6 X CVT-i,Abbottabad,6950000,2026,20,Petrol,1600,Automatic,Toyota,Corolla
858,Toyota Hilux Revo GR-S,Abbottabad,17400000,2026,20,Diesel,2800,Automatic,Toyota,Hilux
859,Toyota Corolla Altis Grande X CVT-i 1.8 Beige ...,Abbottabad,8000000,2026,20,Petrol,1800,Automatic,Toyota,Corolla
861,Toyota Hilux Revo GR-S,Abbottabad,17400000,2026,20,Diesel,2800,Automatic,Toyota,Hilux
4142,Toyota Hilux Revo GR-S,Abbottabad,17400000,2026,20,Diesel,2800,Automatic,Toyota,Hilux